#!/usr/bin/env python3
"""Generate editor local-model configuration from inferctl route state."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse, urlunparse


TARGETS = ("aider", "cline")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate editor config from inferctl route/config JSON."
    )
    parser.add_argument("--target", required=True, choices=TARGETS)
    parser.add_argument("--task", default="code")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--allow-not-ready", action="store_true")
    parser.add_argument("--inferctl", default=os.environ.get("INFERCTL_BIN", "inferctl"))
    args = parser.parse_args()

    try:
        route_env = inferctl_json(args.inferctl, "route", args.task)
        config_env = inferctl_json(args.inferctl, "config", "show")
        artifact, diagnostics = generate(args.target, route_env, config_env, args.allow_not_ready)
        write_output(artifact, args.output, args.overwrite)
        for diagnostic in diagnostics:
            print(diagnostic, file=sys.stderr)
        return 0
    except UserFacingError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return exc.exit_code


class UserFacingError(Exception):
    def __init__(self, message: str, exit_code: int = 1) -> None:
        super().__init__(message)
        self.exit_code = exit_code


def inferctl_json(binary: str, *args: str) -> dict[str, Any]:
    proc = subprocess.run(
        [binary, *args, "--json"],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    try:
        envelope = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        detail = proc.stderr.strip() or proc.stdout.strip()
        raise UserFacingError(f"inferctl {' '.join(args)} did not emit JSON: {detail}") from exc
    if proc.returncode != 0 or not envelope.get("ok", False):
        errors = envelope.get("errors") or []
        if errors:
            first = errors[0]
            message = first.get("message") or first.get("code") or "inferctl command failed"
        else:
            message = proc.stderr.strip() or "inferctl command failed"
        raise UserFacingError(f"inferctl {' '.join(args)} failed: {message}", proc.returncode or 1)
    return envelope


def generate(
    target: str,
    route_env: dict[str, Any],
    config_env: dict[str, Any],
    allow_not_ready: bool,
) -> tuple[str, list[str]]:
    route = route_env.get("data", {})
    decision = route.get("decision", {})
    backend_name = required_string(decision, "selected_backend", "route decision")
    model = required_string(decision, "selected_model", "route decision")
    base_url = selected_base_url(config_env, backend_name)
    api_base = openai_compatible_base_url(base_url)
    diagnostics = route_diagnostics(route_env, decision, allow_not_ready)

    if target == "aider":
        return render_aider(model, api_base), diagnostics
    if target == "cline":
        return render_cline(model, api_base), diagnostics
    raise UserFacingError(f"unknown target {target!r}; valid targets: {', '.join(TARGETS)}")


def selected_base_url(config_env: dict[str, Any], backend_name: str) -> str:
    data = config_env.get("data", {})
    backends = data.get("effective_config", {}).get("backends", {})
    backend = backends.get(backend_name)
    if not isinstance(backend, dict):
        raise UserFacingError(f"selected backend {backend_name!r} is missing from config show output")
    return required_string(backend, "base_url", f"backend {backend_name}")


def route_diagnostics(
    route_env: dict[str, Any],
    decision: dict[str, Any],
    allow_not_ready: bool,
) -> list[str]:
    diagnostics: list[str] = []
    selected = decision.get("selected_model")
    reason = decision.get("reason")
    if decision.get("is_fallback"):
        diagnostics.append(f"warning: generated from fallback route {selected!r}: {reason}")
    if not decision.get("ready", False):
        message = f"selected route {selected!r} is not ready"
        if not allow_not_ready:
            raise UserFacingError(message + "; pass --allow-not-ready to emit config anyway")
        diagnostics.append("warning: " + message)
    for warning in route_env.get("warnings") or []:
        code = warning.get("code")
        if code and code not in {"W_FALLBACK_USED", "W_MODEL_NOT_LOADED"}:
            diagnostics.append(f"warning: inferctl {code}: {warning.get('message', '')}")
    return diagnostics


def render_aider(model: str, api_base: str) -> str:
    return "\n".join(
        [
            "# Generated by examples/editor-configs/generate.py",
            "# inferctl emits config; aider calls the backend directly.",
            f"model: {yaml_quote('openai/' + model)}",
            f"openai-api-base: {yaml_quote(api_base)}",
            "openai-api-key: placeholder",
            "",
        ]
    )


def render_cline(model: str, api_base: str) -> str:
    return "\n".join(
        [
            "# Generated by examples/editor-configs/generate.py",
            "# Paste these values into Cline's OpenAI Compatible provider settings.",
            "api_provider: OpenAI Compatible",
            f"base_url: {yaml_quote(api_base)}",
            f"model_id: {yaml_quote(model)}",
            "api_key: placeholder",
            "",
        ]
    )


def openai_compatible_base_url(base_url: str) -> str:
    parsed = urlparse(base_url)
    path = parsed.path.rstrip("/")
    if path.endswith("/v1") or path == "/v1":
        return urlunparse(parsed._replace(path=path))
    path = (path + "/v1") if path else "/v1"
    return urlunparse(parsed._replace(path=path))


def yaml_quote(value: str) -> str:
    return json.dumps(value)


def required_string(value: dict[str, Any], key: str, context: str) -> str:
    raw = value.get(key)
    if not isinstance(raw, str) or raw == "":
        raise UserFacingError(f"{context} missing string field {key!r}")
    return raw


def write_output(content: str, output: Path | None, overwrite: bool) -> None:
    if output is None:
        print(content, end="")
        return
    if output.exists() and not overwrite:
        raise UserFacingError(f"{output} exists; pass --overwrite to replace it")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
